#!/usr/bin/env bash

set -e

function cleanup_at_exit {
  git checkout master
  git branch -D deploy
}

trap cleanup_at_exit EXIT
git checkout -b deploy
webpack -p
git add -f public/bundle.js public/bundle.js.map
git commit --allow-empty -m 'Deploying'
git push --force heroku deploy:master
